// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0G55CheBLCk2JnuP7FKydNjRdOZiTBIE',
    appId: '1:651467780080:web:e2dbe537bd79b4220fb735',
    messagingSenderId: '651467780080',
    projectId: 'flutter-practice-a990b',
    authDomain: 'flutter-practice-a990b.firebaseapp.com',
    storageBucket: 'flutter-practice-a990b.appspot.com',
    measurementId: 'G-SW6RY3R92F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfl6Vzm9a9IjFnfvhKEHmSXLtMXTwuIwI',
    appId: '1:651467780080:android:7842606d58d268590fb735',
    messagingSenderId: '651467780080',
    projectId: 'flutter-practice-a990b',
    storageBucket: 'flutter-practice-a990b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlCBCfy1Mxh8Pv9MA-nHTy6rhLQX2T5Zs',
    appId: '1:651467780080:ios:2b9868143f047ea00fb735',
    messagingSenderId: '651467780080',
    projectId: 'flutter-practice-a990b',
    storageBucket: 'flutter-practice-a990b.appspot.com',
    iosClientId: '651467780080-80n8jvo95gj6q63s38svc94k45its2e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlCBCfy1Mxh8Pv9MA-nHTy6rhLQX2T5Zs',
    appId: '1:651467780080:ios:2b9868143f047ea00fb735',
    messagingSenderId: '651467780080',
    projectId: 'flutter-practice-a990b',
    storageBucket: 'flutter-practice-a990b.appspot.com',
    iosClientId: '651467780080-80n8jvo95gj6q63s38svc94k45its2e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );
}
